# !! PLEASE NOTE: `minimal.yaml` is meant as a _minimal_ example of a tiny, fast
#                 training that can be used to verify your nequip+allegro install,
#                 the syntax of your configuration edits, etc.
#                 These are NOT recommended hyperparameters for real applications!
#                 Please see `example.yaml` for a reasonable starting point.

# general
root: results/aspirin
run_name: minimal
seed: 123456
dataset_seed: 123456

# -- network --
model_builders:
 - allegro.model.Allegro
 - PerSpeciesRescale
 - StressForceOutput
 - RescaleEnergyEtc

# cutoffs
r_max: 6.0
# optionally, you can specify per-edge-type cutoffs to be applied to the initial basis
per_edge_type_cutoff:
  # These can be given explicitly for each ordered edge type:
  H:
    H: 2.0   # H-H
    C: 2.5   # H-C
    O: 2.1   # H-O
  # or for all edges with a given center type
  C: 5.0     # C-*  (C-H, C-O, C-C)
  O: 6.0     # O-*

# network symmetry
l_max: 1
parity: o3_full  

# allegro layers:
num_layers: 2
num_tensor_features: 32
two_body_latent_mlp_latent_dimensions: [32, 64]
two_body_latent_mlp_nonlinearity: silu
num_bessels_per_basis: 8

latent_mlp_latent_dimensions: [64]
latent_mlp_nonlinearity: silu

latent_resnet: true
latent_resnet_coefficients: [1.0, 1.0, 1.0]
latent_resnet_coefficients_learnable: false

env_embed_mlp_latent_dimensions: []
env_embed_mlp_nonlinearity: null

edge_eng_mlp_latent_dimensions: [32]
edge_eng_mlp_nonlinearity: null

# -- data --
dataset: npz                                                                       # type of data set, can be npz or ase
dataset_url: http://quantum-machine.org/gdml/data/npz/aspirin_ccsd.zip             # url to download the npz. optional
dataset_file_name: ./benchmark_data/aspirin_ccsd-train.npz                         # path to data set file
key_mapping:
  z: atomic_numbers                                                                # atomic species, integers
  E: total_energy                                                                  # total potential eneriges to train to
  F: forces                                                                        # atomic forces to train to
  R: pos                                                                           # raw atomic positions
npz_fixed_field_keys:                                                              # fields that are repeated across different examples
  - atomic_numbers

# A mapping of chemical species to type indexes is necessary if the dataset is provided with atomic numbers instead of type indexes.
chemical_symbol_to_type:
  H: 0
  C: 1
  O: 2

# logging
wandb: false
verbose: info

# training
n_train: 25
n_val: 5
batch_size: 1
max_epochs: 10
learning_rate: 0.002

# loss function
loss_coeffs: forces

# optimizer
optimizer_name: Adam
